In [1]:
#!pip install numpy

In [3]:
import numpy as np

In [7]:
a=np.array([])
b=np.array([2,43,25,31,0])
c=np.array([[131,41],[4,64]])

In [8]:
a

array([], dtype=float64)

In [11]:
type(a)

numpy.ndarray

In [12]:
type(b)

numpy.ndarray

In [13]:
type(c)

numpy.ndarray

In [9]:
b

array([ 2, 43, 25, 31,  0])

In [10]:
c

array([[131,  41],
       [  4,  64]])

In [14]:
a.ndim

1

In [15]:
b.ndim

1

In [16]:
c.ndim

2

In [17]:
a.size

0

In [18]:
b.size

5

In [19]:
c.size

4

In [20]:
c.shape

(2, 2)

In [21]:
#to make row and coloumn
n=np.array([[  2,3,4,5 ]       , [20,34,24,14]        ,  [200,543,525 ,3424   ]  ])

In [22]:
n.shape

(3, 4)

# DAY 2

In [2]:
import numpy as np

In [3]:
n=np.array([[1,23,4,2],[13,432,23,23],[3,2,4,1]])

In [4]:
n


array([[  1,  23,   4,   2],
       [ 13, 432,  23,  23],
       [  3,   2,   4,   1]])

In [5]:
#wrong method
n[0][0]

1

In [6]:
n[0,0]

1

In [8]:
n[2,2]

4

In [9]:
n[1,1]

432

In [10]:
n[1,3]

23

In [13]:
n[2,[0,1]]

array([3, 2])

In [14]:
n.shape

(3, 4)

In [15]:
n[2,1:3]

array([2, 4])

In [ ]:
#syntax=n[row,col]

In [17]:
n[1:,2:]

array([[23, 23],
       [ 4,  1]])

In [18]:
n[1:3,2:4]

array([[23, 23],
       [ 4,  1]])

In [19]:
n[0:,3:]

array([[ 2],
       [23],
       [ 1]])

In [21]:
n[1,:2]

array([ 13, 432])

# arange

In [23]:
list (range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [24]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [25]:
list (range(5.5,50,3))

TypeError: 'float' object cannot be interpreted as an integer

In [26]:
np.arange(5.5,50.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

# Reshape

In [40]:
a=np.arange(12).reshape(4,3)

In [35]:
np.sqrt(131)

11.445523142259598

In [42]:
a.max()

11

In [41]:
a.min()

0

In [43]:
n


array([[  1,  23,   4,   2],
       [ 13, 432,  23,  23],
       [  3,   2,   4,   1]])

In [44]:
n.argmax()

5

In [45]:
n.argmin()

0

In [46]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
a.argmax()

11

In [48]:
a.argmin()

0

In [49]:
n*2

array([[  2,  46,   8,   4],
       [ 26, 864,  46,  46],
       [  6,   4,   8,   2]])

In [50]:
a*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [51]:
a+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

# Random

In [56]:
np.random.rand(2,2)

array([[0.47592404, 0.8812112 ],
       [0.61053647, 0.85790241]])

## 

In [57]:
np.random.rand(2)

array([0.87331922, 0.58253703])

In [58]:
np.random.randn(2,2)

array([[-0.82178843,  0.72202425],
       [ 0.26750952, -0.63723139]])

In [59]:
np.random.randint(9,90)

38

In [66]:
r=np.random.randint(9,90,12).reshape(6,2)

In [67]:
r

array([[19, 79],
       [65, 86],
       [51, 67],
       [59, 53],
       [13, 45],
       [79, 43]])

In [68]:
r.sum()

659

In [72]:
# coloumn wise
r.sum(axis=0)

array([286, 373])

In [74]:
#row wise
r.sum(axis=1)

array([ 98, 151, 118, 112,  58, 122])

# 3D

In [ ]:
d=np.array([ [[4,40],[5,50],[6,60]]  ,  [[7,70],[8,80],[9,90]]  , [[5,55],[4,45],[6,60]] ])

In [ ]:
d.shape

In [ ]:
# nan-not a number


In [3]:
import numpy as np

In [4]:
x=np.array([12,45,np.nan,66,45,np.nan])

In [5]:
x

array([12., 45., nan, 66., 45., nan])

In [7]:
x.dtype


dtype('float64')